fix npe
Cannot invoke "com.intellij.java.language.psi.PsiClass.getQualifiedName()" because "containingClass" is null: Cannot invoke "com.intellij.java.language.psi.PsiClass.getQualifiedName()" because "containingClass" is null
java.lang.NullPointerException: Cannot invoke "com.intellij.java.language.psi.PsiClass.getQualifiedName()" because "containingClass" is null
	at consulo.java/consulo.java@3-SNAPSHOT/com.intellij.java.impl.codeInsight.daemon.impl.quickfix.StaticMembersProcessor.registerMember(StaticMembersProcessor.java:136)
	at consulo.java/consulo.java@3-SNAPSHOT/com.intellij.java.impl.codeInsight.daemon.impl.quickfix.StaticMembersProcessor.getMembersToImport(StaticMembersProcessor.java:69)